source 'https://github.com/FinweLtd/orion360-sdk-pro-ios-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :tvos, "9.0"
workspace 'Hello Orion360 AppleTV'

target "Hello Orion360 AppleTV" do
	# Third party libs
	pod 'orion360-sdk-pro-ios'
end

